version: '3'

networks:
    frontend:
    backend:
volumes:
    postgres-data:
    redis-data:

services:
  proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../../.:/var/www/app
      - ../../docker/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend

  php:
    image: laravelgis-php:latest
    restart: always
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile.dev
    volumes:
      - ../../.:/var/www/app
    ports:
      - "8082:80"
    env_file:
      - ../../.env
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - env/db.dev
    networks:
      - backend

  redis:
    image: redis:latest
    sysctls:
      - net.core.somaxconn=511
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend
